# Site
title:              "Full Stack Sensei"
bio:                "I'm a black belt in geek-do, the not so ancient art of achieving one's goals by merging technology with passion."
description:        "Views on DevOps and SRE from a CTO perspective"
locale:             en_UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fullstacksensei.com" # the base hostname & protocol for your site
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
formspree_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            FullStackSensei
facebook:           default
instagram:          default
github:             geewiz

# personal
location:           Bray, Ireland
phone:              "+353 1901 2642" 
email:              info@fullstacksensei.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
